class EnvironmentSettings:
    def __init__(self):
        self.workspace_dir = '/mnt/data1/sqx/sot'    # Base directory for saving network checkpoints.
        self.tensorboard_dir = '/mnt/data1/sqx/sot/tensorboard'    # Directory for tensorboard files.
        self.pretrained_networks = '/mnt/data1/sqx/sot/pretrained_networks'
        self.lasot_dir = '/mnt/data1/sqx/sot/data/lasot'
        self.got10k_dir = '/mnt/data1/sqx/sot/data/got10k/train'
        self.got10k_val_dir = '/mnt/data1/sqx/sot/data/got10k/val'
        self.lasot_lmdb_dir = '/mnt/data1/sqx/sot/data/lasot_lmdb'
        self.got10k_lmdb_dir = '/mnt/data1/sqx/sot/data/got10k_lmdb'
        self.trackingnet_dir = '/mnt/data1/sqx/sot/data/trackingnet'
        self.trackingnet_lmdb_dir = '/mnt/data1/sqx/sot/data/trackingnet_lmdb'
        self.coco_dir = '/mnt/data1/sqx/sot/data/coco'
        self.coco_lmdb_dir = '/mnt/data1/sqx/sot/data/coco_lmdb'
        self.lvis_dir = ''
        self.sbd_dir = ''
        self.imagenet_dir = '/mnt/data1/sqx/sot/data/vid'
        self.imagenet_lmdb_dir = '/mnt/data1/sqx/sot/data/vid_lmdb'
        self.imagenetdet_dir = ''
        self.ecssd_dir = ''
        self.hkuis_dir = ''
        self.msra10k_dir = ''
        self.davis_dir = ''
        self.youtubevos_dir = ''
        self.dev_dir = '/mnt/data1/sqx/sot/data/dev'
